# -*- coding: utf-8 -*-
"""Node_of_Tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lwEGpBmavSiXWRpr7gTRiLHS4VHSQ9dC
"""

#Create a class and import into the CKY-parser code file

#Objects are- self, root, left, right, end

class Node:  #creating a class 'Node'

	def __init__(self, root, left, right, end):     #defining objects
		
		self._root = root
		self._left = left
		self._right = right
		self._terminal = end

		self._status = True
		if end == None:
			self._status = False

  #Returns the result of the production rule
	@property
	def root(self):	
		return self._root

  #Returns the left child of the production rule
	@property
	def left(self):	
		return self._left

  #Returns the right child of the production rule
	@property
	def right(self):
		return self._right

  #Returns the result of the production rule
	@property
	def status(self):
		return self._status

  #Returns the result of the production rule
	@property
	def terminal(self):
		return self._terminal